### ISSUE TITLE
UI for roll pop ups

### ISSUE THREAD

**Issue by Sparkasaurusmex** [iotech-fvtt/fantasy-ui#4]
It would be awesome to have this cool UI affect the roll pop ups.

**Comment by iotech-fvtt** [comment]
Which roll popups? Core? Better Rolls? Send me a screenshot of an example of the popup you are thinking of, please.

**Comment by Sparkasaurusmex** [comment]
Just the ones from core 5e rolls

**Comment by iotech-fvtt** [comment]
I can do that, though it might be a few days.

**Comment by Sparkasaurusmex** [comment]
Wow, that'd be amazing!  They look so bland after looking at your ui for
everything else

**Comment by iotech-fvtt** [comment]
Hi Sparkasaurusmex! 
Sorry I let this go so long without a reply. Somewhere along the way I did spruce up the chat messages for rolls. Parchment background. Well, maybe it wasnt much of an upgrade. Anyway, I want to stay away from heavy modification of chat elements, because they all use the same css clases, and my changes might look good on a roll popup, but look terrible for other items that get put in chat. So thats why I just stayed with a simple textured background for the chart card.  I'm closing this, but if you still use FantasyUI, I am back in the "code zone" and you're welcome to add a new issue on this (or any other) suggestion.
